apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: light-sleeper
    from-descriptor: yaml
  name: light-sleeper
spec:
  nodeSelector:
    container-runtime: "docker"
  containers:
  - image: debian:10-slim
    name: debian
    resources: {}    
    command: ["bash","-c","sleep 3d"]   
    imagePullPolicy: Always     
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
