apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: yaml-pod
    #from-descriptor: yaml
  name: yaml-pod
spec:
  containers:
  - image: containous/whoami:latest
    name: whoami-in-pod
    ports:
    - containerPort: 80
    resources: {}
  - image: zenika/k8s-training-tools:v1
    name: shell-in-pod
    resources: {}    
    command: ["sleep","infinity"]   
    imagePullPolicy: Always 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
