---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    test: liveness
  annotations:
    what-do-you-like: crash-with-error-500
spec:
  containers:
    - name: i-am-alive
      image: k8s.gcr.io/e2e-test-images/agnhost:2.21
      args:
        - liveness
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 1
        failureThreshold: 5