---
apiVersion: v1
kind: Service
metadata:
  name: multi-ports
spec:
  selector:
    app: multi-ports
    level: expert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web-port
    - protocol: TCP
      port: 8000
      targetPort: 1234
      name: admin-port
